"""Ren'Py Translator - Write translation files under game/tl/<lang>/.

Ren'Py expects translation files inside:
    game/tl/<language>/

We generate a 'strings.rpy' (or similar) file containing translation blocks.
Optionally we can write helper assets used at runtime (filters, etc.).
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict
import re
import json


_RE_ESCAPE = re.compile(r'([\\"])')
_RE_HEX_COLOR = re.compile(r"^#?[0-9a-fA-F]{3}([0-9a-fA-F]{1})?$|^#?[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$")


def _escape_renpy(s: str) -> str:
    return _RE_ESCAPE.sub(r"\\\1", s)


def write_tl_strings_file(
    game_dir: Path,
    lang_code: str,
    translations: Dict[str, str],
    out_name: str = "zz_auto_strings.rpy",
) -> Path:
    """
    Generates: game/tl/<lang_code>/zz_auto_strings.rpy
    using:
        translate <lang_code> strings:
            old "..."
            new "..."
    """
    tl_dir = game_dir / "tl" / lang_code
    tl_dir.mkdir(parents=True, exist_ok=True)
    out_path = tl_dir / out_name

    items = sorted(translations.items(), key=lambda x: x[0])

    lines: list[str] = []
    lines.append("# Auto-generated by Ren'Py Translator — DO NOT EDIT BY HAND")
    lines.append(f"translate {lang_code} strings:")

    for old, new in items:
        old_s = (old or "").strip()
        new_s = (new or "").strip()
        if not old_s or not new_s:
            continue

        # Safety: never write color-like strings
        if _RE_HEX_COLOR.match(old_s) or _RE_HEX_COLOR.match(new_s):
            continue

        old_e = _escape_renpy(old)
        new_e = _escape_renpy(new)
        lines.append(f'    old "{old_e}"')
        lines.append(f'    new "{new_e}"')
        lines.append("")

    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return out_path


def write_runtime_filter_assets(
    game_dir: Path,
    lang_code: str,
    translations: Dict[str, str],
    map_name: str = "rt_map.json",
    rpy_name: str = "zz_runtime_filter.rpy",
) -> tuple[Path, Path]:
    """
    Creates in game/tl/<lang_code>/:
      - rt_map.json : { "old": "new", ... }
      - zz_runtime_filter.rpy : sets config.say_menu_text_filter to translate runtime say/menu texts

    Why it works:
      - tl/<lang_code>/ files are only loaded when that language is active.
      - say/menu statements pass their text through config.say_menu_text_filter.
    """
    tl_dir = game_dir / "tl" / lang_code
    tl_dir.mkdir(parents=True, exist_ok=True)

    map_path = tl_dir / map_name
    rpy_path = tl_dir / rpy_name

    # Filter map: remove empties + hex colors
    clean: dict[str, str] = {}
    for old, new in translations.items():
        o = (old or "").strip()
        n = (new or "").strip()
        if not o or not n:
            continue
        if _RE_HEX_COLOR.match(o) or _RE_HEX_COLOR.match(n):
            continue
        clean[old] = new

    map_path.write_text(json.dumps(clean, ensure_ascii=False, indent=2), encoding="utf-8")

    # This file is loaded ONLY when lang_code is active (because it sits in tl/<lang_code>/)
    # It translates all say/menu texts at runtime via config.say_menu_text_filter.
    rpy_code = f"""# Auto-generated by Ren'Py Translator — DO NOT EDIT BY HAND
# Runtime translation filter for say/menu text (language: {lang_code})

init -2 python:
    import json

    _RT_MAP = {{}}

    def _rt_load_map():
        global _RT_MAP
        try:
            import renpy
            # transfn resolves even when game is packed
            p = renpy.loader.transfn("tl/{lang_code}/{map_name}")
            with open(p, "r", encoding="utf-8") as f:
                _RT_MAP = json.load(f)
        except Exception:
            _RT_MAP = {{}}

    def _rt_filter(s):
        try:
            return _RT_MAP.get(s, s)
        except Exception:
            return s

    _rt_load_map()

# This filters text found in strings in say and menu statements.
define config.say_menu_text_filter = _rt_filter
"""
    rpy_path.write_text(rpy_code, encoding="utf-8")

    return map_path, rpy_path